
server:
  port: 8111
spring:
  application:
    name: userservice
  jpa:
    hibernate:
      ddl-auto:
        create-drop
  datasource:
    url:
      jdbc:mysql://localhost:3306/user_service_ms
    username:
      root
    password:
      ismail
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
